### ISSUE TITLE
Use ENV variable to use `*.r2.dev` API

### ISSUE THREAD

**Issue by tillkruss** [tillkruss/ruddarr#21]
I think we should have a variable to always use the dummy API endpoints, so development is easy.

This should work for preview and simulator builds, maybe macOS too?

https://holyswift.app/best-ways-to-set-up-environment-in-swiftui/

**Comment by pteasima** [comment]
@tillkruss Im a big believer in configuration as a code. Rather than hiding this setting somewhere in environment variables of the build process, I'd like to use Swift to do so. Its ok to then have a little something (preprocessor macro, environment variable), although I usually stop short of that step nad just control this manually from `App.swift` file, e.g. by including `.environment(\.api, .dummy)` (this syntax assumes we're using approach 2. from below)

Currently we have no way of doing Dependency Injection, i.e. substituting arbitrary behavior in place of the `MovieModel.fetch` method (and possibly other "service-layer" objects that "interact with the outside world"). This can be very useful e.g. in SwiftUI previews or unit-testing, where you don't just wanna hit some dummy API URL, but want complete control over what movies are loaded and how. There are many ways of doing this:
1. https://github.com/pointfreeco/swift-dependencies - very clean, great fit for object-heavy architectures. But its a 3rd party framework so not sure how you feel about that.
2. SwiftUI Environment - built-in and easy to use, similar to swift-dependencies, but can only be used directly from views (so only suitable for MVC architecture, hard to get this into our MovieModel) ❌
3. https://vimeo.com/291588126 the most minimal approach - a global configurable struct. This is actuallly super usable I would recommend we just start with that ✅. The downside is, this is global for the whole app/process, so you can't e.g. have two parallel tests using different APIs, but thats usually not an issue.
4. many other popular 3rd frameworks which I consider needlessly overengineered, so I won't list them.

I wanna get your thoughts on this before proceeding, given that you may feel Im overthinking it, you never plan to do any testing, don't care for flexibility when setting up previews or running app in specific scenarios, and you feel that a simple `if simulator { dummyAPI } else { realAPI }` is all you need. Personally, depedency injection is something I include from day one, given that its not much trouble and always comes in handy sooner rather than later.

**Comment by tillkruss** [comment]
I added `PreviewData` in 79572ae and 5891e06, can we leverage this?

**Comment by tillkruss** [comment]
Number 3 sounds great to get things going 👍

**Comment by pteasima** [comment]
Cool, In this task. I'll make the appropriate refactor (minimal scope possible to have dependency injection for fetching movies). We could later expand same approach to any side-effecting code, but we can do that gradually as needed.

**Comment by tillkruss** [comment]
See 7ffe19d120436a00588df2ac30885d33b7b14962 for some initial work.

**Comment by pteasima** [comment]
Ok good to see you're working on it. I can see two class implementations `API` and `DummyAPI`, They are not used anywhere, we never make an instance, they only have static methods that implement the desired behavior.

I assume the plan is still for me to implement global struct-based dependency injection approach like agreed above. I will use the behavior of your API and DummyAPI, although I might not keep all the decorations and might just place this code slightly elsewhere. Will work on that now.

**Comment by pteasima** [comment]
Ok actually `API<MovieCall> is used` but I don't see how we're getting `DummyAPI` when we want (assume it hasn't been implemented). My plan stays the same.
